version: '3.4'

services:
  livemessengerapi:
    image: livemessenger_api:latest
    build:
      context: .
      dockerfile: LiveMessengerApi/Dockerfile
    ports:
      - "80:80"
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    depends_on:
      - cassandra

  cassandra:
    image: thefgut/livemessenger_cassandra_db:latest
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment:
      CASSANDRA_START_RPC: "true"
      CASSANDRA_RPC_ADDRESS: "0.0.0.0"

    stdin_open: true
    tty: true